<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
    <ProjectReference Include="..\OutputAbstractions\OutputAbstractions.csproj" />
        <ProjectReference Include="..\Overlay.WebSockets\Overlay.WebSockets.csproj"/>
        <ProjectReference Include="..\PlatformInput\PlatformInput.csproj"/>
    </ItemGroup>

</Project>
