global using System.Collections.Immutable;
global using System.Diagnostics.CodeAnalysis;
global using System.Text.Json;
global using Collections.Pooled;
global using SharpSticks.Config;
global using SharpSticks.InputAbstractions;
global using SharpSticks.InputSynthesis.Keyboard;
global using SharpSticks.InputSynthesis.Mouse;
global using SharpSticks.OutputAbstractions;
global using SharpSticks.Testing;
global using Xunit;
global using static System.TimeSpan;
global using static SharpSticks.Tests.TestDefaults;